### ISSUE TITLE
Fails to load on 1.18.2

### ISSUE THREAD

**Issue by Boy0000** [DartCat25/resourcepacks#3]
Trying to apply the 1.18.1 pack as its the latest one, but "Resourcepacks failed to load"

**Comment by StormDragon-64** [comment]
I think this is because mojang changed fog in 1.18.1 and then changed it again in 1.18.2, and vanilla shaders do something with that. What pack are you using? There might be instructions on how to fix this on its pmc page.

**Comment by Boy0000** [comment]
Tried using the circular hud one but didnt work.

**Comment by DartCat25** [comment]
Mojangs changed fog in 1.18.2 again. I'll try to fix it soon with some additions, but now you may play with pre-1.18.1 version, because it still works in newer versions but with broken fog.

**Comment by DartCat25** [comment]
Fixed.
