### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by Aceplante2** [DartCat25/resourcepacks#5]

**Comment by DartCat25** [comment]
Download what? All packs in folders have zip that you can download.

**Comment by ZwipZwapZapony** [comment]
This GitHub repository doesn't have any "releases" yet, but you can either...
\- Enter a resource pack's folder in the "_Code_" tab, click on its zip, and click "_Download_" (or "_View raw_") to download it. (This is what DartCat25 suggested.)
\- Go to the main root folder in the "_Code_" tab, click on the green "_Code_" button at the top-right of the file list, choose "_Download ZIP_" to download everything, and extract the resource pack folders that you want.

Neither option works for all resource packs; some only have zips, and some only have loose files.
